[package]
name = "wraptatui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
fluorine = { git = "https://github.com/lasernoises/fluorine.git" }
tui-input = { version = "0.14.0", features = ["crossterm"] }
